### ISSUE TITLE
How do you run the server?

### ISSUE THREAD

**Issue by paulzain** [shiwano/submarine#1]
Very interested in your work...how do you run the local server?

Thanks

**Comment by shiwano** [comment]
Hi, thank you for your interest! 😄 

I assume you are using a Mac which is installed Ruby and Go, MySQL, Redis. You can run the local server with following commands probably.

```sh
# Config

cp config.example.yml config.development.yml

# API Server (This is a normal Rails server)

cd server/api
gem install bundler
bundle install
rake db:setup
rails s -b 0.0.0.0

# Battle Server (This is a customized WebSocket server managed by gb)

cd server/battle
go get github.com/constabulary/gb/...
gb vendor restore
gb build
./bin/app
```

**Comment by kimsama** [comment]
no other chance to run on windows? 

I tried to run on windows, installed rubyinstaller and run 'bundler' but it did not work as expected. :-/

**Comment by kimsama** [comment]
building of API server, got the error:
```
current directory: D:/Util/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/ext/nio4r
D:/Util/Ruby23-x64/bin/ruby.exe -r ./siteconf20161229-21060-e4bwbe.rb extconf.rb --with-cflags=-std=c99
checking for unistd.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl()... no
checking for sys/select.h... no
checking for poll.h... no
checking for sys/epoll.h... no
checking for sys/event.h... no
checking for port.h... no
checking for sys/resource.h... no
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  D:/Util/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/nio4r-1.2.1/mkmf.log

current directory: D:/Util/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/ext/nio4r
make "DESTDIR=" clean

current directory: D:/Util/Ruby23-x64/lib/ruby/gems/2.3.0/gems/nio4r-1.2.1/ext/nio4r
make "DESTDIR="
generating nio4r_ext-x64-mingw32.def
compiling monitor.c
compiling nio4r_ext.c
In file included from nio4r_ext.c:7:0:
../libev/ev.c:1829:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern' [enabled by default]
../libev/ev.c: In function 'evpipe_write':
../libev/ev.c:2466:19: warning: assignment from incompatible pointer type [enabled by default]
compiling selector.c
selector.c: In function 'NIO_Selector_allocate':
selector.c:92:5: warning: implicit declaration of function 'pipe' [-Wimplicit-function-declaration]
selector.c: In function 'NIO_Selector_run':
selector.c:355:9: error: 'TRAP_BEG' undeclared (first use in this function)
selector.c:355:9: note: each undeclared identifier is reported only once for each function it appears in
selector.c:357:9: error: 'TRAP_END' undeclared (first use in this function)
make: *** [selector.o] Error 1

make failed, exit code 2
```

**Comment by shiwano** [comment]
Hi @kimsama, thanks for your trying!

Unfortunety, I dont know right way to build the Ruby environment on Windows, because I have not a Windows machine 😅 .  I am planning to use [Docker](https://www.docker.com/) for building the environment, when it finished,  could you try it again?

**Comment by kimsama** [comment]
@shiwano Sure, why not. I've already got installed Docker on my windows machine. By the way, I'll also try to build it on Windows 10 which can run bash so, I guess it may build as much like OSX. 

Thank you.

**Comment by shiwano** [comment]
@kimsama, I just added support for Docker, so you would be able to run the servers on Windows probably.

I assume you have installed Docker for Windows. You need to take some steps before running the servers. First, create `config.development.yml` from `config.example.yml`.

```sh
cp config.example.yml config.development.yml
```
And edit `config.development.yml` to add your machine's private IP address and database host like below.

```yaml
client:
  version: 1.0.0
  api_server_base_uri: http://192.168.0.1:3000 # Edit!
server:
  api_server_base_uri: http://192.168.0.1:3000 # Edit!
  battle_server_base_uri: ws://192.168.0.1:5000 # Edit!
  database:
    host: mysql # Edit!
    port: 3306
    user: root
    password: ''
```

Last, run the following commands, then you can run the servers.

```sh
rake gen:configs
docker-compose build
docker-compose run api db:setup
docker-compose up
```

**Comment by kimsama** [comment]
Thanks for your efforts.

-Kim

2017년 1월 9일 (월) 오전 5:31, Shogo Iwano <notifications@github.com>님이 작성:

**Comment by kimsama** [comment]
By the way, where can I pull the docker image?

**Comment by shiwano** [comment]
The Docker images which you need will be created on local machine by `docker-compose build` command. The images are defined in [docker\-compose\.yml](https://github.com/shiwano/submarine/blob/master/docker-compose.yml).

**Comment by kimsama** [comment]
Woops. yep. I did not notice there is -compose.yml file. 

Found it and build it now. Thanks :-)

**Comment by kimsama** [comment]
Where the `client/Assets/Resources/Config/Config.json` file? 

Run `rake gen:configs --trace` got the following errors:

![rake-error](https://cloud.githubusercontent.com/assets/564941/21954330/08a4603a-da91-11e6-949c-4f839d770575.png)

**Comment by shiwano** [comment]
@kimsama, sorry, this [commit](https://github.com/shiwano/submarine/commit/b9d830a5f98822c8ac7b856760bacda19109b251)  which I pushed now will fix the issue 😓

**Comment by kimsama** [comment]
With installing [RubyInstaller for windows 2.3.3,](https://rubyinstaller.org/), it successfully runs on Windows10. I guess it does same as on Windows7. 

Thank you again.

**Comment by shiwano** [comment]
Thank you, too! 😃

**Comment by shiwano** [comment]
> EDIT: Didn't you forget to push client/Assets/Resources/Config/Config.json file? There is only Config.meta file in that directory.

I forgot to reply to this. It is as I intended. I'm going to add sensitive data to `config.json` or `Config.json`, so the config files should not be commted to the repo. `Config.meta` should be ignored by `.gitignore` too, it's my mistake.

**Comment by Memphis004** [comment]
OS: windows (Bash on Ubuntu on Windows)
When I try to generate code I see the following error: 
```
 Generating files
[01:15:10][ERROR] Failed to generate a file: src: lib/unity/templates/Unity/WebSocketApi.UniRx.hbs, dest: TyphenApi/Generated/WebSocketApi//Submarine.UniRx.cs, resolvedDest: /mnt/c/w2/src/github.com/shiwano/submarine/client/Assets/Scripts/TyphenApi/Generated/WebSocketApi/Submarine.UniRx.cs, context: Submarine
```
![untitled](https://user-images.githubusercontent.com/7858824/29941077-6bec2da6-8ebb-11e7-9a28-4ddc32d36b8a.jpg)
```
Fatal Error: ENOENT: no such file or directory, open '/mnt/c/w2/src/github.com/shiwano/submarine/tools/typhen/typhen-api/lib/unity/templates/Unity/WebSocketApi.UniRx.hbs'
```
`typhen` work normally.
But can't generate file `Submarine.UniRx.cs` and `Battle.UniRx.cs` ,What should I do? 
Thanks

**Comment by shiwano** [comment]
Umm... I have no experience to operate on Bash on Ubuntu on Windows, so I can't give good advise you maybe.

Can you execute the following commands?

```
cd /mnt/c/w2/src/github.com/shiwano/submarine/tools/typhen/typhen-api/lib/unity/templates/Unity
node -e "var fs = require('fs'); var str = fs.readFileSync('./WebSocketApi.UniRx.hbs', {encoding: 'utf8'}); console.log(str);"
```
