### ISSUE TITLE
WebApiError with Golang

### ISSUE THREAD

**Issue by sleepingwovles** [shiwano/submarine#3]
I try use your typhenAPI  with revel(golang) replace ROR, now it ok I make request and response working normally, request and response in golang I wrote follow your code `web_api_transpoter.go`, but I don’t get it with code Error Handling in ROR , how do write render response WebApiError in golang ? 

P.S.  Very interested in your work and I want to use it.
sorry for bad English, Thanks.

**Comment by Memphis004** [comment]
Focus here code!!
[.../lib/respondable/respondable.go](url) and [.../lib/typhenapi/web/submarine/api.go](url)

**Comment by shiwano** [comment]
Hi, @sleepingwovles

https://github.com/shiwano/submarine/blob/master/server/api/app/controllers/application_controller.rb#L29
https://github.com/shiwano/submarine/blob/master/server/api/app/controllers/concerns/typhen_api_respondable.rb#L10

Error handling code in RoR is here.

https://github.com/shiwano/submarine/blob/master/server/battle/lib/typhenapi/type/submarine/error.go

If you want to handle WebApiError on your web server, you need to serialize this type and send it to client with error HTTP status code (like 400, 500...).

For example, if I will write error handling code in `web_api_transporter.go`, it will be like this.

```go
func (t *WebAPITransporter) RoundTrip(request *http.Request) (*http.Response, error) {
	var typhenType typhenapi.Type
	var statusCode int

	requestData, err := ioutil.ReadAll(request.Body)
	if err != nil {
		typhenType = &api.Error{Code: 1, Name: "BadRequestError", Message: err.Error()}
		statusCode = http.StatusBadRequest
	} else {
		typhenType, statusCode = t.routes(request.URL.Path, requestData)

		if _, ok := typhenType.(*api.Error); !ok && statusCode >= 400 {
			typhenType = &api.Error{Code: 2, Name: "ServerError", Message: "Invalid response body"}
		}

		err := typhenType.Coerce()
		if err != nil {
			typhenType = &api.Error{Code: 3, Name: "CoercionError", Message: err.Error()}
			statusCode = http.StatusInternalServerError
		}
	}

	responseData, err := typhenType.Bytes(t.serializer)
	if err != nil {
		typhenType = &api.Error{Code: 4, Name: "SerializationError", Message: err.Error()}
		statusCode = http.StatusInternalServerError
	}

	response := &http.Response{Header: make(http.Header), Request: request}
	response.Header.Set("Content-Type", "application/json")
	response.StatusCode = statusCode
	response.Body = ioutil.NopCloser(bytes.NewReader(responseData))
	return response, nil
}
```

**Comment by sleepingwovles** [comment]
Yeah!! I got it 
\(• ε •) .oO( Thanks ) :two_hearts:

![Image](https://scontent.fbkk5-5.fna.fbcdn.net/v/t35.0-12/24197378_862752500570463_1036241118_o.jpg?oh=682bd361d8bb59ef221b9ff429ee0286&oe=5A2065D9)
